name: uni
channels:
  - defaults
dependencies:
  - python=3.11  # You can change this to your preferred version
  - pip
  - pip:
      - ultralytics>=8.0.0
      - opencv-python>=4.5.0
      - numpy>=1.20.0
      - tqdm>=4.62.0
      - pyyaml>=6.0
      - pathlib>=1.0.1
      - streamlit
      - fastapi
      - uvicorn
